Implemented patch by Ruben Undheim for allowing a file to be put in the source directory listing all files to be read in during synthesis.  If the file has the default name <project>.fl, then it is used automatically.  Otherwise, the project_vars.sh file has an entry to list the (non-default) filename of this file. Also implements a project_vars.sh file variable "is_system_verilog" to force system-verilog compatibility, to be used when system verilog files simply use the same ".v" extension.

diff --git a/scripts/qflow.sh.in b/scripts/qflow.sh.in
--- a/scripts/qflow.sh.in
+++ b/scripts/qflow.sh.in
@@ -304,19 +304,28 @@ if ($modulename == "") then
 endif
 
 if ($vsource == "") then
-   # Check all .v and .sv files for one with the specified module.
+   # First look for a file list (extension ".fl") that specifies exactly
+   # which modules to use;  this overrides the automatic search for
+   # modules.
+   if ( -f "${sourcedir}/${modulename}.fl" ) then
+      set source_file_list = "${sourcedir}/${modulename}.fl"
+   endif
 
-   foreach file ( `ls ${sourcedir}/*.v ${sourcedir}/*.sv` )
-      set mline = `cat $file | grep module | grep ${modulename} | wc -l`
-      if ( $mline > 0 ) then
-	 set vsource = ${file}
-	 break
+   # If there is no file list, then search for modules with this name.
+   if ( ! ($?source_file_list) ) then
+      # Check all .v and .sv files for one with the specified module.
+      foreach file ( `ls ${sourcedir}/*.v ${sourcedir}/*.sv` )
+         set mline = `cat $file | grep module | grep ${modulename} | wc -l`
+         if ( $mline > 0 ) then
+	    set vsource = ${file}
+	    break
+         endif
+      end
+
+      if ( ${vsource} == "" ) then
+         echo "Error:  No verilog file in ${sourcedir} contains module ${modulename}."
+         exit 1
       endif
-   end
-
-   if ( ${vsource} == "" ) then
-      echo "Error:  No verilog file in ${sourcedir} contains module ${modulename}."
-      exit 1
    endif
 endif
 
@@ -473,6 +482,18 @@ if ( ! -f ${userfile} ) then
       echo \# set fanout_options = \"${fanout_options}\" >> ${userfile}
    else
       echo \# set fanout_options = >> ${userfile}
+   endif
+
+   if ( ${?source_file_list} ) then
+      echo \# set source_file_list = \"${source_file_list}\" >> ${userfile}
+   else
+      echo \# set source_file_list = >> ${userfile}
+   endif
+
+   if ( ${?is_system_verilog} ) then
+      echo \# set is_system_verilog = \"${is_system_verilog}\" >> ${userfile}
+   else
+      echo \# set is_system_verilog = >> ${userfile}
    endif
 
    echo "" >> ${userfile}
