Added files for FreePDK45 to the set of distributed technologies.

diff --git a/scripts/qflow.sh.in b/scripts/qflow.sh.in
--- a/scripts/qflow.sh.in
+++ b/scripts/qflow.sh.in
@@ -34,8 +34,7 @@ if ( $project == "" ) then
    set project=`pwd`
 endif
 
-# Source file is not specified unless given on the command line,
-# or if there is only one source file in the source directory.
+set modulename=""
 set vsource=""
 
 # Don't do anything unless told to on the command line
@@ -46,7 +45,7 @@ set dosynth=0
 set doplace=0
 set dosta=0
 set doroute=0
-set dodecongest=0
+set dobackanno=0
 set doclean=0
 set dodisplay=0
 
@@ -87,6 +86,7 @@ while ($#argv > 0)
 	 shift
 	 breaksw
       case sta:
+      case vesta:
 	 set dosta=1
 	 set actions=1
 	 shift
@@ -96,15 +96,15 @@ while ($#argv > 0)
 	 set actions=1
 	 shift
 	 breaksw
-      case decongest:
-	 set dodecongest=1
+      case backanno:
+	 set dobackanno=1
 	 shift
 	 breaksw
       case build:
 	 set dosynth=1
 	 set doplace=1
 	 set doroute=1
-	 set dodecongest=1
+	 set dobackanno=1
 	 set actions=1
 	 shift
 	 breaksw
@@ -113,7 +113,7 @@ while ($#argv > 0)
 	 set doplace=1
 	 set dosta=1
 	 set doroute=1
-	 set dodecongest=1
+	 set dobackanno=1
 	 set doclean=1
 	 set dodisplay=1
 	 set actions=1
@@ -133,15 +133,19 @@ while ($#argv > 0)
 	 shift
 	 breaksw
       default:
-	 if ($vsource != "") then
+	 if ($modulename != "") then
 	    break
 	 else
-	    set vsource=$argv[1]
+	    set modulename=$argv[1]
 	    shift
 	 endif
 	 breaksw
    endsw
 end
+
+if ($modulename == "") then
+   set dohelp=1
+endif
 
 if ($doversion == 1 || $dohelp == 1) then
    echo "Qflow version QFLOW_VERSION revision QFLOW_REVISION"
@@ -156,17 +160,17 @@ if ($dohelp == 1 || $#argv != 0) then
    echo "Usage: qflow [processes] [options] <module_name>"
    echo "Processes:  synthesize			Synthesize verilog source"
    echo "            place			Run initial placement"
-   echo "	     sta			Static timing analysis"
+   echo "            sta			Static timing analysis"
    echo "            route			Run placement and route"
-   echo "	     decongest			Run congestion analysis, final place and route"
+   echo "            backanno			Post-route timing analysis"
    echo "            clean			Remove temporary working files"
    echo "            display			Display routed result"
    echo ""
-   echo "	     build			Run scripts synthesize to route"
-   echo "	     all			Run scripts synthesize to display"
+   echo "            build			Run scripts synthesize to route"
+   echo "            all			Run scripts synthesize to display"
    echo ""
    echo "Options:    -T, --tech <name>		Use technology <name>"
-   echo "	     -p, --project <name>	Project root directory is <name>"
+   echo "            -p, --project <name>	Project root directory is <name>"
    if ($dohelp == 1) then
       exit 0
    else
@@ -190,18 +194,48 @@ endif
 
 source QFLOW_SCRIPT_DIR/checkdirs.sh ${tech} ${project}
 
-if ($vsource == "") then
-   if (`ls ${sourcedir}/*.v | wc -l` == 1) then
+set nvsrc = `ls ${sourcedir}/*.v | grep -v match | wc -l`
+set nsvsrc = `ls ${sourcedir}/*.sv | wc -l`
+
+# Verilog file root name is the same as the module name, at least until
+# discovered otherwise.  If the module name is not given on the command
+# line, then there must be one source file and the filename root and
+# module name must match.
+
+if ($modulename == "") then
+   if ($nvsrc == 1) then
       set vsource=`ls ${sourcedir}/*.v`
+      set modulename=${vsource:r}
+   else if ($nsvsrc == 1) then
+      set vsource=`ls ${sourcedir}/*.sv`
+      set modulename=${vsource:r}
+   else if ($nvsrc == 0 && $nsvsrc == 0) then
+      echo "Error:  No verilog source files found in directory ${sourcedir}."
+      exit 1
    else
       echo "Error:  No verilog source file or module name has been specified"
       echo "and directory ${sourcedir} contains multiple verilog files."
+      echo "Please specify the source file or module name on the command line."
       exit 1
    endif
 endif
 
-# Module name is the root name of the verilog source file.
-set modulename=${vsource:r}
+if ($vsource == "") then
+   # Check all .v and .sv files for one with the specified module.
+
+   foreach file ( `ls ${sourcedir}/*.v ${sourcedir}/*.sv` )
+      set mline = `cat $file | grep module | grep ${modulename} | wc -l`
+      if ( $mline > 0 ) then
+	 set vsource = ${file}
+	 break
+      endif
+   end
+
+   if ( ${vsource} == "" ) then
+      echo "Error:  No verilog file in ${sourcedir} contains module ${modulename}."
+      exit 1
+   endif
+endif
 
 #------------------------------------------------------------------
 # Source the technology initialization script
@@ -255,7 +289,7 @@ echo "set layoutdir=${layoutdir}" >> ${varfile}
 echo "set techname=${techname}" >> ${varfile}
 echo "set scriptdir=${scriptdir}" >> ${varfile}
 echo "set bindir=${bindir}" >> ${varfile}
-echo "set synthlog=${projectpath}/synth.log" >> ${varfile}
+echo "set logdir=${projectpath}/log" >> ${varfile}
 echo "#-------------------------------------------" >> ${varfile}
 echo "" >> ${varfile}
 
@@ -280,28 +314,127 @@ if ( ! -f ${userfile} ) then
    echo "" >> ${userfile}
    echo "# Synthesis command options:" >> ${userfile}
    echo "# -------------------------------------------" >> ${userfile}
-   echo "# set yosys_options = " >> ${userfile}
-   echo "# set yosys_script = " >> ${userfile}
-   echo "# set yosys_debug = " >> ${userfile}
-   echo "# set abc_script = " >> ${userfile}
-   echo "# set nobuffers = " >> ${userfile}
-   echo "# set nofanout = " >> ${userfile}
-   echo "# set fanout_options = " >> ${userfile}
+
+   #------------------------------------------------------------------
+   # Check for any option defaults set by the .sh file for each entry
+   # in the project_vars.sh file.  If they are not defined, then set
+   # them to an empty string or a global default, if there is one.
+   # Note that this does not change the behavior that options set
+   # in the tech .sh file become the defaults and are overridden by
+   # the same variables set in the project variables file.  The
+   # purpose is to show the user what the default is, so that they
+   # are aware what they may be changing.
+   #------------------------------------------------------------------
+
+   if ( ${?yosys_options} ) then
+      echo \# set yosys_options = \"${yosys_options}\" >> ${userfile}
+   else
+      echo \# set yosys_options = >> ${userfile}
+   endif
+
+   if ( ${?yosys_script} ) then
+      echo \# set yosys_script = \"${yosys_script}\" >> ${userfile}
+   else
+      echo \# set yosys_script = >> ${userfile}
+   endif
+
+   if ( ${?yosys_debug} ) then
+      echo \# set yosys_debug = \"${yosys_debug}\" >> ${userfile}
+   else
+      echo \# set yosys_debug = >> ${userfile}
+   endif
+
+   if ( ${?abc_script} ) then
+      echo \# set abc_script = \"${abc_script}\" >> ${userfile}
+   else
+      echo \# set abc_script = >> ${userfile}
+   endif
+
+   if ( ${?nobuffers} ) then
+      echo \# set nobuffers = \"${nobuffers}\" >> ${userfile}
+   else
+      echo \# set nobuffers = >> ${userfile}
+   endif
+
+   if ( ${?nofanout} ) then
+      echo \# set nofanout = \"${nofanout}\" >> ${userfile}
+   else
+      echo \# set nofanout = >> ${userfile}
+   endif
+
+   if ( ${?fanout_options} ) then
+      echo \# set fanout_options = \"${fanout_options}\" >> ${userfile}
+   else
+      echo \# set fanout_options = >> ${userfile}
+   endif
+
    echo "" >> ${userfile}
    echo "# Placement command options:" >> ${userfile}
    echo "# -------------------------------------------" >> ${userfile}
-   echo "# set initial_density = " >> ${userfile}
-   echo "# set graywolf_options = " >> ${userfile}
+
+   if ( ${?initial_density} ) then
+      echo \# set initial_density = \"${initial_density}\" >> ${userfile}
+   else
+      echo \# set initial_density = >> ${userfile}
+   endif
+
+   if ( ${?graywolf_options} ) then
+      echo \# set graywolf = \"${graywolf_options}\" >> ${userfile}
+   else
+      echo \# set graywolf_options = >> ${userfile}
+   endif
+
+   if ( ${?addspacers_options} ) then
+      echo \# set addspacers_options = \"${addspacers_options}\" >> ${userfile}
+   else
+      echo \# set addspacers_options = >> ${userfile}
+   endif
+
    echo "" >> ${userfile}
    echo "# Router command options:" >> ${userfile}
    echo "# -------------------------------------------" >> ${userfile}
-   echo "# set route_layers = " >> ${userfile}
-   echo "# set via_stacks = " >> ${userfile}
-   echo "# set qrouter_options = " >> ${userfile}
+
+   if ( ${?route_show} ) then
+      echo \# set route_show = \"${route_show}\" >> ${userfile}
+   else
+      echo \# set route_show = >> ${userfile}
+   endif
+
+   if ( ${?route_layers} ) then
+      echo \# set route_layers = \"${route_layers}\" >> ${userfile}
+   else
+      echo \# set route_layers = >> ${userfile}
+   endif
+
+   if ( ${?via_use} ) then
+      echo \# set via_use = \"${via_use}\" >> ${userfile}
+   else
+      echo \# set via_use = >> ${userfile}
+   endif
+
+   if ( ${?via_stacks} ) then
+      echo \# set via_stacks = \"${via_stacks}\" >> ${userfile}
+   else
+      echo \# set via_stacks = >> ${userfile}
+   endif
+
+   if ( ${?qrouter_options} ) then
+      echo \# set qrouter_options = \"${qrouter_options}\" >> ${userfile}
+   else
+      echo \# set qrouter_options = >> ${userfile}
+   endif
+
    echo ""
    echo "" >> ${userfile}
-   echo "# Minimum operating period of the clock (in ps)" >> ${userfile}
-   echo '# set vesta_options = "--period 1E5"' >> ${userfile}
+   echo \# Minimum period of the clock use \"--period value\" \(value in ps\) \
+	>> ${userfile}
+
+   if ( ${?vesta_options} ) then
+      echo \# set vesta_options = \"${vesta_options}\" >> ${userfile}
+   else
+      echo \# set vesta_options = >> ${userfile}
+   endif
+
    echo "" >> ${userfile}
    echo "#------------------------------------------------------------" >> ${userfile}
    echo "" >> ${userfile}
@@ -310,7 +443,11 @@ endif
 if ($dosynth == 0) then
    echo -n "# " >> ${execfile}
 endif
-echo "${scriptdir}/synthesize.sh ${projectpath} ${modulename} || exit 1" >> ${execfile}
+if ( ${vsource} == "" ) then
+   echo "${scriptdir}/synthesize.sh ${projectpath} ${modulename} || exit 1" >> ${execfile}
+else
+   echo "${scriptdir}/synthesize.sh ${projectpath} ${modulename} ${vsource} || exit 1" >> ${execfile}
+endif
 
 if ($doplace == 0) then
    echo -n "# " >> ${execfile}
@@ -329,16 +466,10 @@ if ($doroute == 0) then
 endif
 echo "${scriptdir}/router.sh ${projectpath} ${modulename} || exit 1" >> ${execfile}
 
-if ($dodecongest == 0) then
+if ($dobackanno == 0) then
    echo -n "# " >> ${execfile}
 endif
-echo "${scriptdir}/placement.sh -f -d ${projectpath} ${modulename} || exit 1" >> ${execfile}
-
-if ($dodecongest == 0) then
-   echo -n "# " >> ${execfile}
-endif
-echo -n "${scriptdir}/router.sh ${projectpath} ${modulename} || exit 1" >> ${execfile}
-echo ' $status' >> ${execfile}
+echo "${scriptdir}/vesta.sh -d ${projectpath} ${modulename} || exit 1" >> ${execfile}
 
 if ($doclean == 0) then
    echo -n "# " >> ${execfile}
