Merged all updates from qflow-1.1 into qflow-1.2.  Yes, I'm aware that that's backwards.  qflow-1.2 will now be the development platform in the usual sense.

diff --git a/scripts/qflow.sh.in b/scripts/qflow.sh.in
--- a/scripts/qflow.sh.in
+++ b/scripts/qflow.sh.in
@@ -39,6 +39,7 @@ set vsource=""
 
 # Don't do anything unless told to on the command line
 set actions=0
+set dogui=0
 set dohelp=0
 set doversion=0
 set dosynth=0
@@ -74,6 +75,10 @@ while ($#argv > 0)
 	 set doversion=1
 	 shift
 	 breaksw
+      case gui:
+         set dogui=1
+         shift
+         breaksw
       case synth:
       case synthesize:
 	 set dosynth=1
@@ -143,6 +148,22 @@ while ($#argv > 0)
    endsw
 end
 
+if ($dogui == 1) then
+    # Run interactive GUI interface instead of this script.
+    if ( -f QFLOW_SCRIPT_DIR/qflow_manager.py ) then
+        if ( $has_tech == 0 ) then
+	    exec QFLOW_SCRIPT_DIR/qflow_manager.py $tech $modulename
+	else
+	    exec QFLOW_SCRIPT_DIR/qflow_manager.py None $modulename
+        endif
+	# exec should not return. . .
+	exit 0
+    else
+	echo "GUI manager not installed.  Requires python3"
+	set dohelp = 1
+    endif
+endif
+
 if ($modulename == "") then
    set dohelp=1
 endif
@@ -169,6 +190,8 @@ if ($dohelp == 1 || $#argv != 0) then
    echo "            build			Run scripts synthesize to route"
    echo "            all			Run scripts synthesize to display"
    echo ""
+   echo "            gui			Run the qflow interactive GUI"
+   echo ""
    echo "Options:    -T, --tech <name>		Use technology <name>"
    echo "            -p, --project <name>	Project root directory is <name>"
    if ($dohelp == 1) then
@@ -193,6 +216,11 @@ else
 endif
 
 source QFLOW_SCRIPT_DIR/checkdirs.sh ${tech} ${project}
+if ($status == 1) then
+   echo "Failure to verify working directories."
+   echo "Check QFLOW_PROJECT_ROOT environment variable."
+   exit 1
+endif
 
 set nvsrc = `ls ${sourcedir}/*.v | grep -v match | wc -l`
 set nsvsrc = `ls ${sourcedir}/*.sv | wc -l`
@@ -325,6 +353,12 @@ if ( ! -f ${userfile} ) then
    # purpose is to show the user what the default is, so that they
    # are aware what they may be changing.
    #------------------------------------------------------------------
+
+   if ( ${?hard_macros} ) then
+      echo \# set hard_macros = \"${hard_macros}\" >> ${userfile}
+   else
+      echo \# set hard_macros = >> ${userfile}
+   endif
 
    if ( ${?yosys_options} ) then
       echo \# set yosys_options = \"${yosys_options}\" >> ${userfile}
